#!/bin/bash
# =============================================================
# ProHouzing — VPS Setup Script
# Chạy trên VPS Ubuntu/Debian: bash setup_vps.sh
# =============================================================
set -e

echo "🚀 ProHouzing VPS Setup v2.2.0"
echo "================================"

# ─── 1. Đặt thông tin VPS ────────────────────────────────────
DB_NAME="prohouzing_db"
DB_USER="prohouzing"
DB_PASS="${PROHOUZING_DB_PASS:-$(openssl rand -hex 16)}"
JWT_SECRET="${PROHOUZING_JWT_SECRET:-$(python3 -c 'import secrets; print(secrets.token_hex(32))')}"
PORT="${PORT:-8002}"

echo ""
echo "📋 Config:"
echo "  DB_USER = $DB_USER"
echo "  DB_NAME = $DB_NAME"
echo "  PORT    = $PORT"
echo ""

# ─── 2. Cài PostgreSQL ────────────────────────────────────────
echo "📦 [1/6] Cài PostgreSQL..."
if ! command -v psql &> /dev/null; then
    sudo apt-get update -q
    sudo apt-get install -y postgresql postgresql-contrib
    sudo systemctl start postgresql
    sudo systemctl enable postgresql
    echo "✅ PostgreSQL đã cài"
else
    echo "✅ PostgreSQL đã có sẵn"
fi

# ─── 3. Tạo DB + User ────────────────────────────────────────
echo ""
echo "🗄️  [2/6] Tạo database và user..."
sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';" 2>/dev/null || true
sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || true
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;" 2>/dev/null || true
echo "✅ Database $DB_NAME sẵn sàng"

# ─── 4. Ghi .env.production ──────────────────────────────────
echo ""
echo "📝 [3/6] Ghi file .env.production..."
cat > .env.production << EOF
# ProHouzing Production — auto-generated by setup_vps.sh
# $(date)

# Database
POSTGRES_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}
MONGO_URL=
MONGO_READ_ONLY=true
DB_NAME=${DB_NAME}

# Security
JWT_SECRET=${JWT_SECRET}

# URLs
FRONTEND_URL=https://prohouzing.com
BACKEND_URL=https://api.prohouzing.com
EMAIL_FROM=noreply@prohouzing.com
COOKIE_DOMAIN=.prohouzing.com
CORS_ORIGINS=https://prohouzing.com,https://www.prohouzing.com,https://app.prohouzing.com,http://localhost:3000

# Features
ENABLE_EMAIL=true
ENABLE_ZALO=false
ENABLE_SMS=false
ENABLE_AI=true
ENABLE_KYC=false
RECRUITMENT_DEV_MODE=false
OTP_EXPIRY=300
OTP_MAX_ATTEMPTS=5
PORT=${PORT}
ENV=production
EOF
echo "✅ .env.production đã ghi"

# ─── 5. Cài Python packages ───────────────────────────────────
echo ""
echo "📦 [4/6] Cài Python dependencies..."
pip install -r requirements.txt -q
echo "✅ Dependencies installed"

# ─── 6. Init PostgreSQL tables ────────────────────────────────
echo ""
echo "🗂️  [5/6] Khởi tạo database tables..."
export $(cat .env.production | grep -v '^#' | xargs)
python3 -c "
from core.database import init_db
init_db()
print('✅ Database tables created')
"

# ─── 7. Kiểm tra server syntax ────────────────────────────────
echo ""
echo "🔍 [6/6] Kiểm tra syntax prohouzing_server.py..."
python3 -m py_compile prohouzing_server.py && echo "✅ Syntax OK"

# ─── Done ─────────────────────────────────────────────────────
echo ""
echo "============================================"
echo "✅ Setup hoàn tất!"
echo ""
echo "📋 Thông tin kết nối:"
echo "  POSTGRES_URL = postgresql://$DB_USER:****@localhost:5432/$DB_NAME"
echo "  JWT_SECRET   = ${JWT_SECRET:0:16}..."
echo ""
echo "🚀 Khởi động server:"
echo "  gunicorn prohouzing_server:app \\"
echo "    --workers 2 \\"
echo "    --worker-class uvicorn.workers.UvicornWorker \\"
echo "    --bind 0.0.0.0:$PORT \\"
echo "    --timeout 120 \\"
echo "    --log-level info"
echo ""
echo "  Hoặc dùng: bash start_backend.command"
echo "============================================"
