"""
SITEMAP GENERATOR - PROHOUZING SEO FACTORY
==========================================
Auto-generate sitemap.xml and robots.txt

Features:
- Dynamic sitemap from published pages
- Auto-update on publish
- Google ping for indexing
- robots.txt generation

Author: ProHouzing Engineering
Version: 1.0
"""

from fastapi import APIRouter, Response
from fastapi.responses import PlainTextResponse
from datetime import datetime, timezone
from typing import List
import os
import httpx

# MongoDB
from motor.motor_asyncio import AsyncIOMotorClient

from dotenv import load_dotenv
load_dotenv()

router = APIRouter()

# MongoDB connection
MONGO_URL = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
DB_NAME = os.environ.get('DB_NAME', 'test_database')

client = AsyncIOMotorClient(MONGO_URL)
db = client[DB_NAME]

# Collections
seo_pages_collection = db['seo_pages']

# Site config
SITE_URL = os.environ.get('FRONTEND_URL', 'https://prohouzing.com')


# ===================== SITEMAP GENERATOR =====================

async def generate_sitemap_xml() -> str:
    """Generate sitemap.xml content"""
    
    # Start XML
    xml_content = '<?xml version="1.0" encoding="UTF-8"?>\n'
    xml_content += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    
    # Add homepage
    xml_content += f'''  <url>
    <loc>{SITE_URL}/</loc>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
'''
    
    # Add static pages
    static_pages = [
        ("/du-an", "weekly", "0.9"),
        ("/gioi-thieu", "monthly", "0.7"),
        ("/lien-he", "monthly", "0.6"),
        ("/tin-tuc", "daily", "0.8"),
        ("/blog", "daily", "0.8"),
    ]
    
    for path, freq, priority in static_pages:
        xml_content += f'''  <url>
    <loc>{SITE_URL}{path}</loc>
    <changefreq>{freq}</changefreq>
    <priority>{priority}</priority>
  </url>
'''
    
    # Add SEO landing pages
    async for page in seo_pages_collection.find({"status": "published", "content_type": "landing"}):
        slug = page.get("slug", "")
        published_at = page.get("published_at", page.get("created_at"))
        lastmod = published_at.strftime("%Y-%m-%d") if published_at else datetime.now().strftime("%Y-%m-%d")
        
        xml_content += f'''  <url>
    <loc>{SITE_URL}/{slug}</loc>
    <lastmod>{lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
'''
    
    # Add SEO blog pages
    async for page in seo_pages_collection.find({"status": "published", "content_type": "blog"}):
        slug = page.get("slug", "")
        published_at = page.get("published_at", page.get("created_at"))
        lastmod = published_at.strftime("%Y-%m-%d") if published_at else datetime.now().strftime("%Y-%m-%d")
        
        xml_content += f'''  <url>
    <loc>{SITE_URL}/blog/{slug}</loc>
    <lastmod>{lastmod}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
'''
    
    xml_content += '</urlset>'
    
    return xml_content


def generate_robots_txt() -> str:
    """Generate robots.txt content"""
    return f"""# ProHouzing Robots.txt
# Generated by SEO Engine

User-agent: *
Allow: /

# Disallow admin areas
Disallow: /admin/
Disallow: /api/
Disallow: /login
Disallow: /dashboard/

# Sitemap location
Sitemap: {SITE_URL}/sitemap.xml

# Crawl-delay for politeness
Crawl-delay: 1
"""


async def ping_google_sitemap():
    """Ping Google to update sitemap"""
    sitemap_url = f"{SITE_URL}/sitemap.xml"
    ping_url = f"https://www.google.com/ping?sitemap={sitemap_url}"
    
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(ping_url)
            if response.status_code == 200:
                print("[SITEMAP] Google ping successful")
                return {"success": True, "message": "Google notified"}
            else:
                print(f"[SITEMAP] Google ping failed: {response.status_code}")
                return {"success": False, "error": f"Status: {response.status_code}"}
    except Exception as e:
        print(f"[SITEMAP] Google ping error: {e}")
        return {"success": False, "error": str(e)}


# ===================== API ENDPOINTS =====================

@router.get("/sitemap.xml", response_class=Response)
async def get_sitemap():
    """Get sitemap.xml"""
    xml_content = await generate_sitemap_xml()
    return Response(
        content=xml_content,
        media_type="application/xml",
        headers={"Content-Type": "application/xml; charset=utf-8"}
    )


@router.get("/robots.txt", response_class=PlainTextResponse)
async def get_robots():
    """Get robots.txt"""
    return generate_robots_txt()


@router.post("/ping-google")
async def api_ping_google():
    """Manually ping Google for sitemap update"""
    result = await ping_google_sitemap()
    return result


@router.get("/stats")
async def api_sitemap_stats():
    """Get sitemap statistics"""
    total_landing = await seo_pages_collection.count_documents({
        "status": "published",
        "content_type": "landing"
    })
    total_blog = await seo_pages_collection.count_documents({
        "status": "published",
        "content_type": "blog"
    })
    
    # Static pages count
    static_count = 6  # homepage + 5 static
    
    return {
        "total_urls": static_count + total_landing + total_blog,
        "static_pages": static_count,
        "landing_pages": total_landing,
        "blog_pages": total_blog,
        "sitemap_url": f"{SITE_URL}/sitemap.xml",
        "robots_url": f"{SITE_URL}/robots.txt"
    }
