const normalizePathname = (path = '/') => {
  if (!path) return '/';

  try {
    return new URL(path, 'http://localhost').pathname || '/';
  } catch (_error) {
    return path.split('?')[0] || '/';
  }
};

export const BACKEND_CONTRACT_STATUS = {
  LOCKED: 'locked',
  INTERNAL: 'internal',
};

export const GO_LIVE_BACKEND_CONTRACTS = [
  {
    key: 'auth.login',
    domain: 'auth',
    label: 'Đăng nhập',
    method: 'POST',
    endpoint: '/api/auth/login',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Nền tảng',
    consumer: 'Toàn hệ thống',
    routePrefixes: ['/login'],
    requestShape: 'email, password',
    responseShape: 'access_token, user',
  },
  {
    key: 'auth.me',
    domain: 'auth',
    label: 'Hồ sơ đăng nhập',
    method: 'GET',
    endpoint: '/api/auth/me',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Nền tảng',
    consumer: 'Toàn hệ thống',
    routePrefixes: ['/me'],
    requestShape: 'Bearer token',
    responseShape: 'user profile, role, scope',
  },
  {
    key: 'workspace.home',
    domain: 'workspace',
    label: 'Workspace theo role',
    method: 'GET',
    endpoint: '/api/workspace',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Platform',
    consumer: 'Toàn hệ thống',
    routePrefixes: ['/workspace', '/dashboard'],
    requestShape: 'role, scope, period',
    responseShape: 'widgets, queues, quick_actions, alerts',
  },
  {
    key: 'app.home',
    domain: 'app',
    label: 'Ứng dụng kinh doanh theo role',
    method: 'GET',
    endpoint: '/api/app/home',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Platform + Sales',
    consumer: 'Sales, Agency, Manager, BOD, Marketing',
    routePrefixes: ['/app'],
    requestShape: 'role, scope, runtime surface',
    responseShape: 'stats, quick_actions, alerts, sections',
  },
  {
    key: 'crm.leads.list',
    domain: 'crm',
    label: 'Danh sách lead',
    method: 'GET',
    endpoint: '/api/leads',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CRM',
    consumer: 'Sales, Marketing, Manager',
    routePrefixes: ['/crm/leads'],
    requestShape: 'status, source, search, pagination',
    responseShape: 'items, total, pagination',
  },
  {
    key: 'crm.contacts.list',
    domain: 'crm',
    label: 'Danh sách khách hàng',
    method: 'GET',
    endpoint: '/api/customers',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CRM',
    consumer: 'Sales, Manager, Agency',
    routePrefixes: ['/crm/contacts'],
    requestShape: 'status, owner, search, pagination',
    responseShape: 'items, total, pagination',
  },
  {
    key: 'crm.demands.list',
    domain: 'crm',
    label: 'Nhu cầu khách',
    method: 'GET',
    endpoint: '/api/demands',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CRM',
    consumer: 'Sales, Manager',
    routePrefixes: ['/crm/demands'],
    requestShape: 'status, budget, area, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'sales.pipeline',
    domain: 'sales',
    label: 'Pipeline giao dịch',
    method: 'GET',
    endpoint: '/api/sales/deals/pipeline',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Sales',
    consumer: 'Sales, Manager',
    routePrefixes: ['/sales', '/sales/pipeline', '/sales/deals', '/sales/kanban'],
    requestShape: 'project_id, stage',
    responseShape: 'total_deals, total_value, by_stage',
  },
  {
    key: 'sales.soft-bookings',
    domain: 'sales',
    label: 'Giữ chỗ tạm',
    method: 'GET',
    endpoint: '/api/sales/soft-bookings',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Sales',
    consumer: 'Sales, Manager, BOD',
    routePrefixes: ['/sales/soft-bookings', '/sales/bookings'],
    requestShape: 'project_id, status, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'sales.hard-bookings',
    domain: 'sales',
    label: 'Giữ chỗ chính thức',
    method: 'GET',
    endpoint: '/api/sales/hard-bookings',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Sales',
    consumer: 'Sales, Manager, BOD',
    routePrefixes: ['/sales/hard-bookings'],
    requestShape: 'project_id, status, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'sales.events',
    domain: 'sales',
    label: 'Sự kiện mở bán',
    method: 'GET',
    endpoint: '/api/sales/events',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Sales',
    consumer: 'Sales, Marketing, Manager',
    routePrefixes: ['/sales/events'],
    requestShape: 'project_id, status, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'sales.stage-config',
    domain: 'sales',
    label: 'Cấu hình stage',
    method: 'GET',
    endpoint: '/api/sales/config/deal-stages',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Sales',
    consumer: 'Sales, Manager',
    routePrefixes: ['/sales', '/sales/pricing', '/sales/product-center', '/sales/products', '/sales/projects', '/sales/knowledge-center', '/sales/channel-center'],
    requestShape: 'none',
    responseShape: 'stages[]',
  },
  {
    key: 'marketing.campaigns',
    domain: 'marketing',
    label: 'Chiến dịch marketing',
    method: 'GET',
    endpoint: '/api/marketing/campaigns',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Marketing',
    consumer: 'Marketing, Manager',
    routePrefixes: ['/marketing', '/marketing/campaigns', '/marketing/rules'],
    requestShape: 'status, channel, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'marketing.sources',
    domain: 'marketing',
    label: 'Nguồn khách',
    method: 'GET',
    endpoint: '/api/marketing/sources',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Marketing',
    consumer: 'Marketing, Sales',
    routePrefixes: ['/marketing/sources', '/communications/channels'],
    requestShape: 'channel, status',
    responseShape: 'items, performance',
  },
  {
    key: 'marketing.forms',
    domain: 'marketing',
    label: 'Form marketing',
    method: 'GET',
    endpoint: '/api/marketing/forms',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Marketing',
    consumer: 'Marketing, CMS',
    routePrefixes: ['/marketing/forms', '/communications/forms'],
    requestShape: 'status, source',
    responseShape: 'items, stats',
  },
  {
    key: 'marketing.content',
    domain: 'marketing',
    label: 'Nội dung marketing',
    method: 'GET',
    endpoint: '/api/marketing/content',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Marketing',
    consumer: 'Marketing, Content, Sales',
    routePrefixes: ['/marketing/content', '/communications/content', '/communications/templates'],
    requestShape: 'status, owner, channel, pagination',
    responseShape: 'items, approvalQueue, publishState',
  },
  {
    key: 'marketing.attribution',
    domain: 'marketing',
    label: 'Attribution',
    method: 'GET',
    endpoint: '/api/marketing/attribution',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Marketing',
    consumer: 'Marketing, BOD',
    routePrefixes: ['/marketing/attribution', '/communications/attribution'],
    requestShape: 'period, campaign',
    responseShape: 'summary, channels',
  },
  {
    key: 'finance.dashboard',
    domain: 'finance',
    label: 'Dashboard tài chính',
    method: 'GET',
    endpoint: '/api/finance/dashboard/ceo',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Finance',
    consumer: 'Finance, BOD',
    routePrefixes: ['/finance', '/finance/overview', '/control', '/control/alerts', '/sales/finance-center'],
    requestShape: 'period, branch',
    responseShape: 'summary, alerts, widgets',
  },
  {
    key: 'finance.expenses',
    domain: 'finance',
    label: 'Phiếu chi',
    method: 'GET',
    endpoint: '/api/finance/expenses',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Finance',
    consumer: 'Finance, BOD',
    routePrefixes: ['/finance/expense', '/finance/expenses'],
    requestShape: 'status, branch, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'finance.receivables',
    domain: 'finance',
    label: 'Công nợ phải thu',
    method: 'GET',
    endpoint: '/api/finance/receivables',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Finance',
    consumer: 'Finance, BOD',
    routePrefixes: ['/finance/receivables'],
    requestShape: 'status, due_date, pagination',
    responseShape: 'items, total, aging',
  },
  {
    key: 'finance.commissions',
    domain: 'finance',
    label: 'Hoa hồng',
    method: 'GET',
    endpoint: '/api/finance/commissions',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Finance',
    consumer: 'Finance, Sales, Agency',
    routePrefixes: ['/finance/commission', '/finance/commissions', '/commission', '/finance/my-income'],
    requestShape: 'status, owner, period',
    responseShape: 'items, summary',
  },
  {
    key: 'payroll.core',
    domain: 'payroll',
    label: 'Bảng lương',
    method: 'GET',
    endpoint: '/api/payroll',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'HR / Finance',
    consumer: 'Finance, HR',
    routePrefixes: ['/payroll'],
    requestShape: 'month, branch',
    responseShape: 'summary, items',
  },
  {
    key: 'payroll.attendance',
    domain: 'payroll',
    label: 'Chấm công',
    method: 'GET',
    endpoint: '/api/payroll/attendance',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'HR',
    consumer: 'HR',
    routePrefixes: ['/payroll/attendance'],
    requestShape: 'date, branch, anomaly',
    responseShape: 'items, summary',
  },
  {
    key: 'hr.recruitment',
    domain: 'hr',
    label: 'Tuyển dụng',
    method: 'GET',
    endpoint: '/api/hr/recruitment',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'HR',
    consumer: 'HR',
    routePrefixes: ['/hr/recruitment'],
    requestShape: 'status, position, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'hr.employees',
    domain: 'hr',
    label: 'Hồ sơ nhân sự',
    method: 'GET',
    endpoint: '/api/hr/employees',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'HR',
    consumer: 'HR, Manager',
    routePrefixes: ['/hr', '/hr/employees', '/hr/organization', '/hr/contracts'],
    requestShape: 'status, org_unit, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'hr.training',
    domain: 'hr',
    label: 'Đào tạo',
    method: 'GET',
    endpoint: '/api/hr/training',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'HR',
    consumer: 'HR, Sales, Manager',
    routePrefixes: ['/hr/training', '/training'],
    requestShape: 'status, assignee, pagination',
    responseShape: 'courses, schedules',
  },
  {
    key: 'legal.licenses',
    domain: 'legal',
    label: 'Pháp lý dự án',
    method: 'GET',
    endpoint: '/api/legal/licenses',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Legal',
    consumer: 'Legal, Sales, BOD',
    routePrefixes: ['/legal/licenses'],
    requestShape: 'status, project, alert',
    responseShape: 'items, progress',
  },
  {
    key: 'legal.contracts',
    domain: 'legal',
    label: 'Hợp đồng pháp lý',
    method: 'GET',
    endpoint: '/api/contracts',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Legal',
    consumer: 'Legal, Sales, BOD',
    routePrefixes: ['/contracts', '/contracts/pending', '/sales/contracts', '/legal/contracts'],
    requestShape: 'status, signer, pagination',
    responseShape: 'items, total',
  },
  {
    key: 'legal.compliance',
    domain: 'legal',
    label: 'Compliance pháp lý',
    method: 'GET',
    endpoint: '/api/legal/compliance',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Legal',
    consumer: 'Legal, BOD',
    routePrefixes: ['/legal/compliance', '/legal/regulations', '/legal/approvals'],
    requestShape: 'status, type, project, pagination',
    responseShape: 'items, alerts, approvals',
  },
  {
    key: 'work.tasks',
    domain: 'work',
    label: 'Công việc',
    method: 'GET',
    endpoint: '/api/tasks',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Work OS',
    consumer: 'Toàn hệ thống nội bộ',
    routePrefixes: ['/work', '/work/tasks'],
    requestShape: 'status, assignee, type',
    responseShape: 'items, total',
  },
  {
    key: 'work.calendar',
    domain: 'work',
    label: 'Lịch làm việc',
    method: 'GET',
    endpoint: '/api/calendar',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Work OS',
    consumer: 'Toàn hệ thống nội bộ',
    routePrefixes: ['/work/calendar'],
    requestShape: 'date, type, assignee',
    responseShape: 'events[]',
  },
  {
    key: 'work.reminders',
    domain: 'work',
    label: 'Nhắc việc',
    method: 'GET',
    endpoint: '/api/reminders',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Work OS',
    consumer: 'Toàn hệ thống nội bộ',
    routePrefixes: ['/work/reminders'],
    requestShape: 'type, source',
    responseShape: 'items, unreadCount',
  },
  {
    key: 'kpi.dashboard',
    domain: 'kpi',
    label: 'KPI dashboard',
    method: 'GET',
    endpoint: '/api/kpis',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Performance',
    consumer: 'Sales, Manager, HR',
    routePrefixes: ['/kpi', '/sales/kpi'],
    requestShape: 'view, role, period',
    responseShape: 'summary, leaderboard',
  },
  {
    key: 'kpi.core',
    domain: 'kpi',
    label: 'KPI core runtime',
    method: 'GET',
    endpoint: '/api/kpis',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Performance',
    consumer: 'Sales, Manager, HR',
    routePrefixes: ['/kpi', '/sales/kpi'],
    requestShape: 'view, role, period',
    responseShape: 'summary, leaderboard',
  },
  {
    key: 'analytics.executive',
    domain: 'analytics',
    label: 'Báo cáo điều hành',
    method: 'GET',
    endpoint: '/api/analytics/executive',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'BI',
    consumer: 'BOD, Admin',
    routePrefixes: ['/analytics'],
    requestShape: 'period, dimension',
    responseShape: 'summary, charts, bottlenecks',
  },
  {
    key: 'cms.dashboard',
    domain: 'cms',
    label: 'Dashboard website / CMS',
    method: 'GET',
    endpoint: '/api/cms/dashboard',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CMS',
    consumer: 'Content, Admin',
    routePrefixes: ['/cms'],
    requestShape: 'status, section',
    responseShape: 'summary, alerts',
  },
  {
    key: 'cms.pages',
    domain: 'cms',
    label: 'Trang website',
    method: 'GET',
    endpoint: '/api/cms/pages',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CMS',
    consumer: 'Content, Admin',
    routePrefixes: ['/cms/pages'],
    requestShape: 'status, type, search',
    responseShape: 'items, total',
  },
  {
    key: 'cms.articles',
    domain: 'cms',
    label: 'Bài viết',
    method: 'GET',
    endpoint: '/api/cms/articles',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CMS',
    consumer: 'Content, Admin',
    routePrefixes: ['/cms/articles'],
    requestShape: 'status, category, search',
    responseShape: 'items, total',
  },
  {
    key: 'cms.analytics',
    domain: 'cms',
    label: 'Phân tích website / CMS',
    method: 'GET',
    endpoint: '/api/cms/analytics',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CMS',
    consumer: 'Content, Admin',
    routePrefixes: ['/cms', '/cms/analytics'],
    requestShape: 'period, section, source',
    responseShape: 'summary, charts, trends',
  },
  {
    key: 'cms.projects',
    domain: 'cms',
    label: 'Dự án hiển thị',
    method: 'GET',
    endpoint: '/api/cms/public-projects',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'CMS',
    consumer: 'Content, Admin',
    routePrefixes: ['/cms/public-projects'],
    requestShape: 'status, project, search',
    responseShape: 'items, total',
  },
  {
    key: 'settings.users',
    domain: 'settings',
    label: 'Người dùng',
    method: 'GET',
    endpoint: '/api/users',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Platform',
    consumer: 'Admin',
    routePrefixes: ['/settings/users'],
    requestShape: 'status, role, org',
    responseShape: 'items, total',
  },
  {
    key: 'settings.roles',
    domain: 'settings',
    label: 'Vai trò & quyền',
    method: 'GET',
    endpoint: '/api/rbac/roles',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Platform',
    consumer: 'Admin',
    routePrefixes: ['/settings/roles'],
    requestShape: 'none',
    responseShape: 'roles[]',
  },
  {
    key: 'settings.governance',
    domain: 'settings',
    label: 'Governance',
    method: 'GET',
    endpoint: '/api/config/governance/*',
    status: BACKEND_CONTRACT_STATUS.LOCKED,
    owner: 'Platform',
    consumer: 'Admin',
    routePrefixes: ['/settings', '/settings/governance', '/settings/governance-coverage', '/settings/governance-remediation', '/settings/change-management'],
    requestShape: 'scope, status',
    responseShape: 'summary, items',
  },
];

export const getGoLiveBackendContracts = () => GO_LIVE_BACKEND_CONTRACTS;

export const getBackendContractsForPath = (path = '/') => {
  const pathname = normalizePathname(path);

  return GO_LIVE_BACKEND_CONTRACTS.filter((contract) =>
    (contract.routePrefixes || []).some((prefix) => pathname === prefix || pathname.startsWith(`${prefix}/`)),
  );
};

export const areBackendContractsLockedForPath = (path = '/') => {
  const contracts = getBackendContractsForPath(path);
  if (!contracts.length) return false;
  return contracts.every((contract) => contract.status === BACKEND_CONTRACT_STATUS.LOCKED);
};

export const getBackendContractSummary = () => {
  const allContracts = getGoLiveBackendContracts();
  const lockedContracts = allContracts.filter((contract) => contract.status === BACKEND_CONTRACT_STATUS.LOCKED);
  const groupedByDomain = allContracts.reduce((accumulator, contract) => {
    accumulator[contract.domain] = accumulator[contract.domain] || [];
    accumulator[contract.domain].push(contract);
    return accumulator;
  }, {});

  return {
    totalContracts: allContracts.length,
    lockedContracts: lockedContracts.length,
    fullyLocked: allContracts.length > 0 && allContracts.length === lockedContracts.length,
    domains: Object.keys(groupedByDomain).length,
  };
};
