import { DEFAULT_DASHBOARD, ROLES } from '@/config/navigation';
import { getRoleSurfaceStrategy, PLATFORM_SURFACE_META } from '@/config/platformSurfaceStrategy';

export const DEMO_PASSWORD = 'admin123';

export const ROLE_ORDER = [
  ROLES.ADMIN,
  ROLES.AUDIT,
  ROLES.BOD,
  ROLES.PROJECT_DIRECTOR,
  ROLES.MANAGER,
  ROLES.SALES,
  ROLES.SALES_SUPPORT,
  ROLES.MARKETING,
  ROLES.FINANCE,
  ROLES.HR,
  ROLES.LEGAL,
  ROLES.CONTENT,
  ROLES.AGENCY,
];

export const ROLE_GOVERNANCE = {
  [ROLES.ADMIN]: {
    code: ROLES.ADMIN,
    ten: 'Quản trị hệ thống',
    capBac: 'Quản trị',
    mang: 'Điều hành',
    moTa: 'Kiểm soát toàn bộ cấu hình, người dùng, phân quyền, quy trình và website.',
    phamVi: 'Toàn doanh nghiệp',
    uuTien: 'Khóa quyền, cấu hình hệ thống, giám sát thay đổi',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.ADMIN],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.ADMIN)?.primarySurface]?.label,
  },
  [ROLES.BOD]: {
    code: ROLES.BOD,
    ten: 'Lãnh đạo',
    capBac: 'Lãnh đạo',
    mang: 'Điều hành',
    moTa: 'Theo dõi toàn cảnh kinh doanh, tài chính, nhân sự, pháp lý và các cảnh báo.',
    phamVi: 'Toàn doanh nghiệp',
    uuTien: 'Ra quyết định, phê duyệt, xem báo cáo chiến lược',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.BOD],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.BOD)?.primarySurface]?.label,
  },
  [ROLES.MANAGER]: {
    code: ROLES.MANAGER,
    ten: 'Quản lý',
    capBac: 'Quản lý',
    mang: 'Kinh doanh',
    moTa: 'Quản lý đội nhóm, theo dõi hiệu suất, phê duyệt và điều phối công việc.',
    phamVi: 'Chi nhánh / phòng ban / đội nhóm',
    uuTien: 'Điều hành đội nhóm và xử lý hàng đợi cần duyệt',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.MANAGER],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.MANAGER)?.primarySurface]?.label,
  },
  [ROLES.SALES]: {
    code: ROLES.SALES,
    ten: 'Nhân viên kinh doanh',
    capBac: 'Nhân viên',
    mang: 'Kinh doanh',
    moTa: 'Xử lý khách hàng, giao dịch, đặt chỗ, hợp đồng và kết quả cá nhân.',
    phamVi: 'Dữ liệu được giao',
    uuTien: 'Làm việc với khách hàng và chốt giao dịch',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.SALES],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.SALES)?.primarySurface]?.label,
  },
  [ROLES.MARKETING]: {
    code: ROLES.MARKETING,
    ten: 'Nhân viên marketing',
    capBac: 'Nhân viên',
    mang: 'Marketing',
    moTa: 'Quản lý chiến dịch, nguồn khách, nội dung, SEO và dữ liệu marketing.',
    phamVi: 'Dữ liệu được giao',
    uuTien: 'Tăng trưởng nguồn khách và hiệu quả truyền thông',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.MARKETING],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.MARKETING)?.primarySurface]?.label,
  },
  [ROLES.FINANCE]: {
    code: ROLES.FINANCE,
    ten: 'Nhân viên tài chính',
    capBac: 'Nhân viên',
    mang: 'Tài chính',
    moTa: 'Theo dõi thu chi, công nợ, hoa hồng, lương và đối soát.',
    phamVi: 'Phòng tài chính',
    uuTien: 'Kiểm soát dòng tiền và số liệu tài chính',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.FINANCE],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.FINANCE)?.primarySurface]?.label,
  },
  [ROLES.HR]: {
    code: ROLES.HR,
    ten: 'Nhân viên nhân sự',
    capBac: 'Nhân viên',
    mang: 'Nhân sự',
    moTa: 'Phụ trách tuyển dụng, hồ sơ nhân sự, cộng tác viên và đào tạo.',
    phamVi: 'Phòng nhân sự',
    uuTien: 'Tuyển dụng và phát triển đội ngũ',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.HR],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.HR)?.primarySurface]?.label,
  },
  [ROLES.LEGAL]: {
    code: ROLES.LEGAL,
    ten: 'Nhân viên pháp lý',
    capBac: 'Nhân viên',
    mang: 'Pháp lý',
    moTa: 'Kiểm soát hợp đồng, hồ sơ pháp lý dự án và rủi ro tuân thủ.',
    phamVi: 'Phòng pháp lý',
    uuTien: 'Đảm bảo hồ sơ và giao dịch đúng quy định',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.LEGAL],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.LEGAL)?.primarySurface]?.label,
  },
  [ROLES.CONTENT]: {
    code: ROLES.CONTENT,
    ten: 'Nhân viên website / CMS',
    capBac: 'Nhân viên',
    mang: 'Website / CMS',
    moTa: 'Quản trị website, trang nội dung, landing page và xuất bản nội dung.',
    phamVi: 'Website / CMS',
    uuTien: 'Vận hành website và nội dung bán hàng',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.CONTENT],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.CONTENT)?.primarySurface]?.label,
  },
  [ROLES.AGENCY]: {
    code: ROLES.AGENCY,
    ten: 'Cộng tác viên / Đại lý',
    capBac: 'Cộng tác viên',
    mang: 'Kinh doanh',
    moTa: 'Giới thiệu khách mua sản phẩm sơ cấp, theo dõi hoa hồng giới thiệu.',
    phamVi: 'Dữ liệu của cá nhân',
    uuTien: 'Giới thiệu khách và theo dõi hoa hồng',
    defaultDashboard: DEFAULT_DASHBOARD[ROLES.AGENCY],
    nenTangChinh: PLATFORM_SURFACE_META[getRoleSurfaceStrategy(ROLES.AGENCY)?.primarySurface]?.label,
  },
  [ROLES.AUDIT]: {
    code: ROLES.AUDIT,
    ten: 'Ban Kiểm soát / HĐQT',
    capBac: 'Quản trị',
    mang: 'Quản trị công ty',
    moTa: 'Giám sát toàn bộ hoạt động, tài chính, nhân sự theo Luật DN 2020. Báo cáo lên ĐHĐCĐ.',
    phamVi: 'Toàn hệ thống (read-only)',
    uuTien: 'Kiểm toán, giám sát, cảnh báo bất thường',
    defaultDashboard: '/app',
    nenTangChinh: 'Mobile App',
  },
  [ROLES.PROJECT_DIRECTOR]: {
    code: ROLES.PROJECT_DIRECTOR,
    ten: 'Giám đốc Dự án',
    capBac: 'Quản lý',
    mang: 'Kinh doanh',
    moTa: 'Quản lý toàn bộ hoạt động bán hàng và đội ngũ tại một dự án cụ thể.',
    phamVi: 'Trong phạm vi project_code',
    uuTien: 'Duyệt booking, theo dõi KPI dự án, quan hệ chủ đầu tư',
    defaultDashboard: '/app',
    nenTangChinh: 'Mobile App',
  },
  [ROLES.SALES_SUPPORT]: {
    code: ROLES.SALES_SUPPORT,
    ten: 'Hỗ trợ nghiệp vụ',
    capBac: 'Nhân viên',
    mang: 'Vận hành',
    moTa: 'Xử lý hồ sơ, booking, hợp đồng sau chốt. Chăm sóc khách hàng sau ký.',
    phamVi: 'Deals đang phụ trách',
    uuTien: 'Xử lý hồ sơ booking, CSKH after-sales',
    defaultDashboard: '/app',
    nenTangChinh: 'Mobile App',
  },
};

export const DEMO_ACCOUNTS = {

  // ── HỆ THỐNG ──────────────────────────────────────────────────────────────────
  'admin@prohouze.com': {
    id: 'local-demo-admin',
    email: 'admin@prohouze.com',
    full_name: 'Quản trị hệ thống',
    role: ROLES.ADMIN,
    department: 'management',
    position: 'System Administrator',
    branch_name: 'Hệ thống',
    branch_code: null,
    phone: '0901 000 001',
  },

  // ── BAN KIỂM SOÁT / HĐQT ──────────────────────────────────────────────────────
  'chutichhd@prohouze.com': {
    id: 'local-demo-chairman',
    email: 'chutichhd@prohouze.com',
    full_name: 'Trịnh Quốc Hùng',
    role: ROLES.AUDIT,
    department: 'governance',
    position: 'Chủ tịch HĐQT',
    branch_name: 'Hội sở',
    branch_code: null,
    phone: '0901 000 100',
  },

  // ── TỔNG GIÁM ĐỐC (BOD) ───────────────────────────────────────────────────────
  'ceo@prohouze.com': {
    id: 'local-demo-ceo',
    email: 'ceo@prohouze.com',
    full_name: 'Nguyễn Minh Tuấn',
    role: ROLES.BOD,
    department: 'management',
    position: 'Tổng Giám đốc',
    branch_name: 'Toàn hệ thống',
    branch_code: null,
    phone: '0901 000 002',
  },

  // ── GIÁM ĐỐC DỰ ÁN ───────────────────────────────────────────────────────────
  'gdda.hcm@prohouze.com': {
    id: 'local-demo-pdirector-hcm',
    email: 'gdda.hcm@prohouze.com',
    full_name: 'Phạm Đình Khánh',
    role: ROLES.PROJECT_DIRECTOR,
    department: 'sales',
    position: 'Giám đốc Dự án',
    branch_name: 'TP. Hồ Chí Minh',
    branch_code: '79',
    project_code: 'VGP-HCM',
    project_name: 'Vinhomes Grand Park HCM',
    phone: '0901 100 001',
  },

  // ── TRƯỞNG NHÓM KINH DOANH (MANAGER) ─────────────────────────────────────────
  'manager@prohouze.com': {
    id: 'local-demo-manager',
    email: 'manager@prohouze.com',
    full_name: 'Lê Anh Dũng',
    role: ROLES.MANAGER,
    department: 'sales',
    position: 'Trưởng nhóm Kinh doanh',
    branch_name: 'TP. Hồ Chí Minh',
    branch_code: '79',
    project_code: 'VGP-HCM',
    phone: '0901 000 003',
  },

  // ── CHUYÊN VIÊN KINH DOANH (SALES) ───────────────────────────────────────────
  'sales@prohouze.com': {
    id: 'local-demo-sales',
    email: 'sales@prohouze.com',
    full_name: 'Trần Văn Minh',
    role: ROLES.SALES,
    department: 'sales',
    position: 'Chuyên viên Kinh doanh',
    branch_name: 'TP. Hồ Chí Minh',
    branch_code: '79',
    project_code: 'VGP-HCM',
    phone: '0912 000 001',
    referral_code: 'TVMINH2024',
  },

  // ── HỖ TRỢ NGHIỆP VỤ (SALES_SUPPORT) ────────────────────────────────────────
  'salesadmin@prohouze.com': {
    id: 'local-demo-salesadmin',
    email: 'salesadmin@prohouze.com',
    full_name: 'Nguyễn Thị Kim Oanh',
    role: ROLES.SALES_SUPPORT,
    department: 'sales_ops',
    position: 'Hỗ trợ Nghiệp vụ',
    branch_name: 'TP. Hồ Chí Minh',
    branch_code: '79',
    project_code: 'VGP-HCM',
    phone: '0901 300 001',
  },

  // ── CỘNG TÁC VIÊN (AGENCY) ───────────────────────────────────────────────────
  'agency@prohouze.com': {
    id: 'local-demo-agency',
    email: 'agency@prohouze.com',
    full_name: 'Nguyễn Thị Lan',
    role: ROLES.AGENCY,
    department: 'external',
    position: 'Cộng tác viên',
    branch_name: 'Khu vực Bình Dương',
    branch_code: null,
    phone: '0933 000 001',
    referral_code: 'NTLAN2024',
  },

  // ── BỘ PHẬN CHỨC NĂNG ────────────────────────────────────────────────────────
  'marketing@prohouze.com': {
    id: 'local-demo-marketing',
    email: 'marketing@prohouze.com',
    full_name: 'Đinh Quỳnh Anh',
    role: ROLES.MARKETING,
    department: 'marketing',
    position: 'Marketing Manager',
    branch_name: 'Hội sở',
    branch_code: null,
    phone: '0901 000 006',
  },
  'finance@prohouze.com': {
    id: 'local-demo-finance',
    email: 'finance@prohouze.com',
    full_name: 'Vũ Thành Long',
    role: ROLES.FINANCE,
    department: 'finance',
    position: 'Kế toán trưởng',
    branch_name: 'Hội sở',
    branch_code: null,
    phone: '0901 000 007',
  },
  'hr@prohouze.com': {
    id: 'local-demo-hr',
    email: 'hr@prohouze.com',
    full_name: 'Đặng Thị Mai',
    role: ROLES.HR,
    department: 'hr',
    position: 'HR Manager',
    branch_name: 'Hội sở',
    branch_code: null,
    phone: '0901 000 008',
  },
  'legal@prohouze.com': {
    id: 'local-demo-legal',
    email: 'legal@prohouze.com',
    full_name: 'Bùi Hoàng Sơn',
    role: ROLES.LEGAL,
    department: 'legal',
    position: 'Trưởng phòng Pháp lý',
    branch_name: 'Hội sở',
    branch_code: null,
    phone: '0901 000 009',
  },
  'content@prohouze.com': {
    id: 'local-demo-content',
    email: 'content@prohouze.com',
    full_name: 'Ngô Thu Trà',
    role: ROLES.CONTENT,
    department: 'content',
    position: 'Content Manager',
    branch_name: 'Hội sở',
    branch_code: null,
    phone: '0901 000 012',
  },
}

export const ROLE_PERMISSION_GROUPS = [
  {
    id: 'dieu_hanh',
    label: 'Điều hành & báo cáo',
    actions: [
      {
        label: 'Xem tình hình doanh nghiệp',
        access: {
          admin: 'Toàn quyền',
          bod: 'Toàn bộ',
          manager: 'Đội nhóm phụ trách',
          sales: 'Tổng quan cá nhân',
          marketing: 'Số liệu marketing',
          finance: 'Số liệu tài chính',
          hr: 'Số liệu nhân sự',
          legal: 'Số liệu pháp lý',
          content: 'Số liệu website',
          agency: 'Tổng quan cá nhân',
        },
      },
      {
        label: 'Duyệt các yêu cầu quan trọng',
        access: {
          admin: 'Thiết lập quy trình',
          bod: 'Duyệt cấp cao',
          manager: 'Duyệt theo đội',
          sales: 'Không',
          marketing: 'Không',
          finance: 'Duyệt tài chính nội bộ',
          hr: 'Duyệt hồ sơ nhân sự',
          legal: 'Duyệt pháp lý',
          content: 'Không',
          agency: 'Không',
        },
      },
    ],
  },
  {
    id: 'kinh_doanh',
    label: 'Khách hàng & giao dịch',
    actions: [
      {
        label: 'Xem và chăm sóc khách hàng',
        access: {
          admin: 'Toàn bộ',
          bod: 'Toàn bộ',
          manager: 'Theo phòng / đội',
          sales: 'Khách được giao',
          marketing: 'Nguồn khách marketing',
          finance: 'Chỉ xem giao dịch liên quan',
          hr: 'Không',
          legal: 'Chỉ xem hồ sơ cần xử lý',
          content: 'Không',
          agency: 'Khách của mình',
        },
      },
      {
        label: 'Tạo giao dịch / đặt chỗ',
        access: {
          admin: 'Toàn bộ',
          bod: 'Theo dõi',
          manager: 'Theo phòng / đội',
          sales: 'Được tạo',
          marketing: 'Không',
          finance: 'Không',
          hr: 'Không',
          legal: 'Không',
          content: 'Không',
          agency: 'Tạo yêu cầu gửi khách',
        },
      },
    ],
  },
  {
    id: 'tai_chinh',
    label: 'Tiền bạc & hoa hồng',
    actions: [
      {
        label: 'Xem doanh thu, thu chi, công nợ',
        access: {
          admin: 'Toàn bộ',
          bod: 'Toàn bộ',
          manager: 'Theo phòng / dự án',
          sales: 'Chỉ phần liên quan',
          marketing: 'Không',
          finance: 'Toàn bộ',
          hr: 'Chỉ lương thưởng',
          legal: 'Không',
          content: 'Không',
          agency: 'Hoa hồng của mình',
        },
      },
      {
        label: 'Khóa số liệu / đối soát',
        access: {
          admin: 'Thiết lập',
          bod: 'Phê duyệt',
          manager: 'Không',
          sales: 'Không',
          marketing: 'Không',
          finance: 'Thực hiện',
          hr: 'Không',
          legal: 'Không',
          content: 'Không',
          agency: 'Không',
        },
      },
    ],
  },
  {
    id: 'nhan_su',
    label: 'Nhân sự & đào tạo',
    actions: [
      {
        label: 'Xem hồ sơ nhân sự và cộng tác viên',
        access: {
          admin: 'Toàn bộ',
          bod: 'Toàn bộ',
          manager: 'Đội nhóm phụ trách',
          sales: 'Hồ sơ của mình',
          marketing: 'Hồ sơ của mình',
          finance: 'Chỉ phần lương thưởng',
          hr: 'Toàn bộ',
          legal: 'Chỉ hồ sơ hợp đồng',
          content: 'Hồ sơ của mình',
          agency: 'Hồ sơ của mình',
        },
      },
      {
        label: 'Tuyển dụng / đào tạo',
        access: {
          admin: 'Thiết lập',
          bod: 'Phê duyệt',
          manager: 'Đề xuất / theo dõi',
          sales: 'Không',
          marketing: 'Không',
          finance: 'Không',
          hr: 'Thực hiện',
          legal: 'Rà soát hợp đồng',
          content: 'Không',
          agency: 'Không',
        },
      },
    ],
  },
  {
    id: 'phap_ly_website',
    label: 'Pháp lý, website & hệ thống',
    actions: [
      {
        label: 'Quản lý hợp đồng, pháp lý dự án',
        access: {
          admin: 'Toàn bộ',
          bod: 'Toàn bộ',
          manager: 'Theo dự án phụ trách',
          sales: 'Chỉ hồ sơ liên quan',
          marketing: 'Không',
          finance: 'Chỉ hồ sơ thanh toán',
          hr: 'Hợp đồng lao động',
          legal: 'Toàn bộ',
          content: 'Không',
          agency: 'Không',
        },
      },
      {
        label: 'Quản trị website, nội dung và phân quyền',
        access: {
          admin: 'Toàn bộ',
          bod: 'Theo dõi',
          manager: 'Theo phạm vi được giao',
          sales: 'Không',
          marketing: 'Nội dung / chiến dịch',
          finance: 'Không',
          hr: 'Không',
          legal: 'Kiểm tra nội dung pháp lý',
          content: 'Website / CMS',
          agency: 'Không',
        },
      },
    ],
  },
];

export const getRoleGovernanceList = () => ROLE_ORDER.map((role) => ROLE_GOVERNANCE[role]).filter(Boolean);

export const getDemoAccountsList = () =>
  Object.values(DEMO_ACCOUNTS).sort(
    (a, b) => ROLE_ORDER.indexOf(a.role) - ROLE_ORDER.indexOf(b.role)
  );
