import {
  AlertTriangle,
  Briefcase,
  Building2,
  CheckSquare,
  DollarSign,
  FileText,
  Globe,
  LayoutDashboard,
  Shield,
  TrendingUp,
  Users,
} from 'lucide-react';

export const roleVisualTone = {
  admin: {
    accent: '#316585',
    softBg: 'bg-[#316585]/[0.06]',
    softBorder: 'border-[#316585]/15',
    softText: 'text-[#316585]',
    chipBg: 'bg-[#316585]/10',
    chipText: 'text-[#316585]',
    heroTitle: 'Khóa chuẩn hệ thống',
  },
  bod: {
    accent: '#7c3aed',
    softBg: 'bg-violet-500/[0.06]',
    softBorder: 'border-violet-500/15',
    softText: 'text-violet-700',
    chipBg: 'bg-violet-500/10',
    chipText: 'text-violet-700',
    heroTitle: 'Ra quyết định hôm nay',
  },
  manager: {
    accent: '#0f766e',
    softBg: 'bg-teal-500/[0.06]',
    softBorder: 'border-teal-500/15',
    softText: 'text-teal-700',
    chipBg: 'bg-teal-500/10',
    chipText: 'text-teal-700',
    heroTitle: 'Đẩy nhịp đội nhóm',
  },
  marketing: {
    accent: '#db2777',
    softBg: 'bg-pink-500/[0.06]',
    softBorder: 'border-pink-500/15',
    softText: 'text-pink-700',
    chipBg: 'bg-pink-500/10',
    chipText: 'text-pink-700',
    heroTitle: 'Tăng khách từ kênh',
  },
  finance: {
    accent: '#b45309',
    softBg: 'bg-amber-500/[0.06]',
    softBorder: 'border-amber-500/15',
    softText: 'text-amber-700',
    chipBg: 'bg-amber-500/10',
    chipText: 'text-amber-700',
    heroTitle: 'Giữ chắc dòng tiền',
  },
  hr: {
    accent: '#2563eb',
    softBg: 'bg-blue-500/[0.06]',
    softBorder: 'border-blue-500/15',
    softText: 'text-blue-700',
    chipBg: 'bg-blue-500/10',
    chipText: 'text-blue-700',
    heroTitle: 'Giữ nhịp đội ngũ',
  },
  legal: {
    accent: '#475569',
    softBg: 'bg-slate-500/[0.06]',
    softBorder: 'border-slate-500/15',
    softText: 'text-slate-700',
    chipBg: 'bg-slate-500/10',
    chipText: 'text-slate-700',
    heroTitle: 'Gỡ nghẽn pháp lý',
  },
  content: {
    accent: '#0891b2',
    softBg: 'bg-cyan-500/[0.06]',
    softBorder: 'border-cyan-500/15',
    softText: 'text-cyan-700',
    chipBg: 'bg-cyan-500/10',
    chipText: 'text-cyan-700',
    heroTitle: 'Giữ trang web sẵn sàng',
  },
  agency: {
    accent: '#16a34a',
    softBg: 'bg-green-500/[0.06]',
    softBorder: 'border-green-500/15',
    softText: 'text-green-700',
    chipBg: 'bg-green-500/10',
    chipText: 'text-green-700',
    heroTitle: 'Chốt khách của mình',
  },
};

export const roleWorkspaceUx = {
  admin: {
    heroKicker: 'Ưu tiên số 1',
    actionsTitle: 'Mở đúng chỗ cần khóa',
    actionsSubtitle: 'Các điểm vào quan trọng nhất của quản trị hệ thống.',
    focusTitle: 'Bản đồ ngày làm việc',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng điều hành',
  },
  bod: {
    heroKicker: 'Quyết định số 1',
    actionsTitle: 'Mở nhanh để ra quyết định',
    actionsSubtitle: 'Đi thẳng vào nơi cần xem và phê duyệt.',
    focusTitle: 'Bản đồ ngày điều hành',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng điều hành',
  },
  manager: {
    heroKicker: 'Việc cần đẩy đầu tiên',
    actionsTitle: 'Mở nhanh để điều hành đội',
    actionsSubtitle: 'Ưu tiên khách nóng, việc quá hạn và KPI đội.',
    focusTitle: 'Bản đồ ngày quản lý',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng làm việc của đội',
  },
  marketing: {
    heroKicker: 'Việc cần đẩy đầu tiên',
    actionsTitle: 'Mở nhanh để kéo khách',
    actionsSubtitle: 'Đi thẳng vào chiến dịch, nội dung và nguồn khách.',
    focusTitle: 'Bản đồ ngày marketing',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng tăng trưởng',
  },
  finance: {
    heroKicker: 'Khoản cần khóa đầu tiên',
    actionsTitle: 'Mở nhanh để giữ chắc số liệu',
    actionsSubtitle: 'Đi thẳng vào công nợ, phiếu chi và hoa hồng.',
    focusTitle: 'Bản đồ ngày tài chính',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng kiểm soát tài chính',
  },
  hr: {
    heroKicker: 'Việc cần xử lý đầu tiên',
    actionsTitle: 'Mở nhanh để giữ nhịp nhân sự',
    actionsSubtitle: 'Đi thẳng vào tuyển dụng, hồ sơ và đào tạo.',
    focusTitle: 'Bản đồ ngày nhân sự',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng vận hành nhân sự',
  },
  legal: {
    heroKicker: 'Hồ sơ cần rà đầu tiên',
    actionsTitle: 'Mở nhanh để gỡ nghẽn pháp lý',
    actionsSubtitle: 'Đi thẳng vào hợp đồng, hồ sơ dự án và tài liệu cho kinh doanh.',
    focusTitle: 'Bản đồ ngày pháp lý',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng kiểm soát pháp lý',
  },
  content: {
    heroKicker: 'Điểm chạm cần sửa đầu tiên',
    actionsTitle: 'Mở nhanh để giữ trang web sẵn sàng',
    actionsSubtitle: 'Đi thẳng vào trang, nội dung, biểu mẫu và hiệu suất trang web.',
    focusTitle: 'Bản đồ ngày trang web & nội dung',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng vận hành trang web',
  },
  agency: {
    heroKicker: 'Khách cần bám đầu tiên',
    actionsTitle: 'Mở nhanh để chốt khách',
    actionsSubtitle: 'Đi thẳng vào khách, booking, hoa hồng và tài liệu mới.',
    focusTitle: 'Bản đồ ngày cộng tác viên',
    supportTitle: 'Hệ thống đang giúp bạn',
    successTitle: 'Kết thúc ngày tốt khi',
    groupsTitle: 'Các vùng làm việc của bạn',
  },
};

export const roleWorkspaceConfig = {
  admin: {
    title: 'Trung tâm quản trị',
    subtitle: 'Kiểm soát quyền, cấu hình, quy trình, dữ liệu chuẩn và tình trạng toàn hệ thống.',
    highlights: [
      { label: 'Yêu cầu chờ duyệt', value: '12', note: 'Phân quyền, dữ liệu chuẩn, thay đổi cấu hình', icon: Shield, link: '/settings/change-management' },
      { label: 'Người dùng đang hoạt động', value: '186', note: 'Toàn công ty và đối tác đang truy cập', icon: Users, link: '/settings/users' },
      { label: 'Mục cần xử lý hôm nay', value: '8', note: 'Cảnh báo bảo mật, quyền và quy trình', icon: AlertTriangle, link: '/settings/governance-coverage' },
      { label: 'Trang web & nội dung', value: 'Ổn định', note: 'Theo dõi xuất bản và nội dung công khai', icon: Globe, link: '/cms' },
    ],
    focus: ['Phân quyền', 'Quy trình & phê duyệt', 'Dữ liệu chuẩn', 'Trang web & nội dung'],
    queue: ['Rà soát thay đổi phân quyền', 'Kiểm tra cảnh báo hệ thống', 'Duyệt cấu hình cần áp dụng'],
  },
  bod: {
    title: 'Bảng điều hành lãnh đạo',
    subtitle: 'Nhìn toàn cảnh doanh nghiệp, biết ngay kinh doanh, tài chính, nhân sự và cảnh báo cần quyết định.',
    highlights: [
      { label: 'Doanh thu tháng', value: '24,8 tỷ', note: 'Đang chạy so với kế hoạch tháng', icon: DollarSign, link: '/finance' },
      { label: 'Khách nóng cần xử lý', value: '31', note: 'Các cơ hội có khả năng chốt cao', icon: TrendingUp, link: '/crm/leads?status=hot' },
      { label: 'Yêu cầu chờ phê duyệt', value: '9', note: 'Giữ chỗ, chi phí, hợp đồng, phân quyền', icon: CheckSquare, link: '/contracts/pending' },
      { label: 'Cảnh báo doanh nghiệp', value: '5', note: 'Tài chính, pháp lý, nhân sự, trang web', icon: AlertTriangle, link: '/workspace' },
    ],
    focus: ['Kinh doanh', 'Tài chính', 'Nhân sự', 'Pháp lý'],
    queue: ['Xem mục chờ phê duyệt', 'Kiểm tra doanh thu và cảnh báo', 'Ra quyết định cho chiến dịch đang đẩy'],
  },
  manager: {
    title: 'Bảng điều hành quản lý',
    subtitle: 'Điều hành đội nhóm, biết ai đang dẫn đầu, ai đang tắc và việc nào cần đẩy ngay.',
    highlights: [
      { label: 'Đội đang theo', value: '48 giao dịch', note: 'Phễu giao dịch còn mở trong tuần này', icon: Briefcase, link: '/sales/deals' },
      { label: 'Nhân sự hoạt động', value: '16', note: 'Sale và cộng tác viên đang làm việc', icon: Users, link: '/hr/organization' },
      { label: 'Việc đội quá hạn', value: '7', note: 'Cần nhắc và gỡ ngay trong ngày', icon: CheckSquare, link: '/work/tasks?status=overdue' },
      { label: 'Top team tuần này', value: '#2 khu vực', note: 'Thi đua theo doanh số và KPI', icon: TrendingUp, link: '/sales/kpi' },
    ],
    focus: ['Đội nhóm', 'KPI & hiệu suất', 'Khách hàng', 'Giao dịch'],
    queue: ['Gỡ việc quá hạn của đội', 'Đẩy khách nóng và giữ chỗ chờ duyệt', 'Bám top kinh doanh và KPI đội'],
  },
  marketing: {
    title: 'Bảng điều hành marketing',
    subtitle: 'Theo dõi kênh, chiến dịch, nội dung và lượng khách đổ về để hỗ trợ kinh doanh tốt hơn.',
    highlights: [
      { label: 'Chiến dịch đang chạy', value: '11', note: 'Bao gồm Meta, Zalo, TikTok và trang đích', icon: TrendingUp, link: '/marketing/campaigns' },
      { label: 'Khách mới hôm nay', value: '84', note: 'Khách mới từ các kênh marketing', icon: Users, link: '/crm/leads?group=source' },
      { label: 'Nội dung cần xuất bản', value: '6', note: 'Bài viết, trang đích, video, biểu mẫu', icon: FileText, link: '/marketing/content' },
      { label: 'Kênh nổi bật', value: 'Facebook', note: 'Đang mang khách tốt nhất tuần này', icon: Globe, link: '/marketing/sources' },
    ],
    focus: ['Chiến dịch', 'Nguồn khách', 'Nội dung', 'Tối ưu tìm kiếm / theo dõi'],
    queue: ['Kiểm tra khách mới về hôm nay', 'Đẩy kênh hiệu quả', 'Xuất bản nội dung đang chờ'],
  },
  finance: {
    title: 'Bảng điều hành tài chính',
    subtitle: 'Theo dõi doanh thu, thu chi, công nợ, hoa hồng và các khoản cần kiểm soát trong ngày.',
    highlights: [
      { label: 'Doanh thu ghi nhận', value: '24,8 tỷ', note: 'Tính đến thời điểm hiện tại', icon: DollarSign, link: '/finance' },
      { label: 'Chi phí chờ duyệt', value: '14', note: 'Phiếu chi và đề xuất tài chính', icon: CheckSquare, link: '/finance/expenses' },
      { label: 'Công nợ cần đối soát', value: '7 hồ sơ', note: 'Cần xử lý để chốt số liệu', icon: AlertTriangle, link: '/finance/receivables' },
      { label: 'Hoa hồng chờ chi', value: '3,2 tỷ', note: 'Cần xác nhận trước khi chi trả', icon: Users, link: '/commission' },
    ],
    focus: ['Doanh thu', 'Thu chi', 'Công nợ', 'Hoa hồng'],
    queue: ['Đối soát công nợ', 'Xử lý phiếu chi chờ duyệt', 'Kiểm tra hoa hồng chờ chi'],
  },
  hr: {
    title: 'Bảng điều hành nhân sự',
    subtitle: 'Bám tuyển dụng, nhân sự, đào tạo và tình trạng hoạt động để giữ guồng vận hành doanh nghiệp.',
    highlights: [
      { label: 'Ứng viên mới', value: '26', note: 'Cần sàng lọc và gọi lại', icon: Users, link: '/hr/recruitment' },
      { label: 'Nhân sự đang hoạt động', value: '132', note: 'Bao gồm chính thức và cộng tác viên', icon: Briefcase, link: '/hr/employees' },
      { label: 'Đào tạo tuần này', value: '4 buổi', note: 'Các lớp cần chuẩn bị và nhắc lịch', icon: FileText, link: '/training' },
      { label: 'Hồ sơ cần hoàn tất', value: '9', note: 'Xác minh hồ sơ, hợp đồng, hồ sơ tiếp nhận', icon: CheckSquare, link: '/hr/employees' },
    ],
    focus: ['Tuyển dụng', 'Hồ sơ nhân sự', 'Đào tạo', 'Lộ trình thăng tiến'],
    queue: ['Gọi ứng viên mới', 'Hoàn tất hồ sơ tiếp nhận', 'Chốt lịch đào tạo tuần này'],
  },
  legal: {
    title: 'Bảng điều hành pháp lý',
    subtitle: 'Theo dõi hồ sơ pháp lý dự án, hợp đồng và những điểm rủi ro cần xử lý ngay.',
    highlights: [
      { label: 'Hồ sơ đang xử lý', value: '18', note: 'Pháp lý dự án và hồ sơ giao dịch', icon: FileText, link: '/legal/licenses' },
      { label: 'Hợp đồng chờ rà soát', value: '11', note: 'Cần kiểm tra trước khi ký', icon: Shield, link: '/contracts/pending' },
      { label: 'Rủi ro cần chú ý', value: '4', note: 'Các điểm pháp lý đang cần theo bám', icon: AlertTriangle, link: '/legal/licenses' },
      { label: 'Tài liệu sẵn gửi kinh doanh', value: '22 bộ', note: 'Dùng để hỗ trợ chốt khách', icon: Globe, link: '/legal/licenses' },
    ],
    focus: ['Hồ sơ pháp lý dự án', 'Hợp đồng', 'Tiến độ xử lý', 'Cảnh báo rủi ro'],
    queue: ['Rà soát hợp đồng chờ ký', 'Cập nhật hồ sơ pháp lý cho kinh doanh', 'Xử lý điểm rủi ro tồn đọng'],
  },
  content: {
    title: 'Bảng điều hành trang web & nội dung',
    subtitle: 'Quản lý nội dung công khai, dự án hiển thị, bài viết và các điểm chạm khách hàng trên trang web.',
    highlights: [
      { label: 'Trang cần cập nhật', value: '8', note: 'Dự án, trang đích, trang thương hiệu', icon: Globe, link: '/cms' },
      { label: 'Bài viết chờ xuất bản', value: '5', note: 'Nội dung trang web và chiến dịch', icon: FileText, link: '/marketing/content' },
      { label: 'Biểu mẫu đang chạy', value: '13', note: 'Các điểm lấy khách trên trang web', icon: Users, link: '/marketing/forms' },
      { label: 'Lỗi tối ưu tìm kiếm / hiển thị', value: '3', note: 'Cần xử lý để không mất lượng truy cập', icon: AlertTriangle, link: '/cms/analytics' },
    ],
    focus: ['Trang', 'Dự án hiển thị', 'Bài viết', 'Biểu mẫu lấy khách'],
    queue: ['Cập nhật trang dự án', 'Xuất bản nội dung chờ duyệt', 'Kiểm tra biểu mẫu và nút kêu gọi hành động đang chạy'],
  },
  agency: {
    title: 'Bảng làm việc cộng tác viên',
    subtitle: 'Chỉ giữ đúng việc cần làm: khách của tôi, giao dịch của tôi, hoa hồng của tôi và tài liệu bán hàng.',
    highlights: [
      { label: 'Khách đang theo', value: '12', note: 'Những khách cần bám trong ngày', icon: Users, link: '/crm/leads' },
      { label: 'Giữ chỗ đang mở', value: '3', note: 'Đang cần xử lý tiếp', icon: Briefcase, link: '/sales/bookings' },
      { label: 'Hoa hồng dự kiến', value: '18 triệu', note: 'Cập nhật theo giao dịch gần nhất', icon: DollarSign, link: '/finance/my-income' },
      { label: 'Tài liệu mới', value: '7', note: 'Bảng giá, chính sách, hồ sơ giới thiệu', icon: FileText, link: '/sales/knowledge-center?tab=dao-tao' },
    ],
    focus: ['Khách hàng', 'Bán hàng', 'Tài chính', 'Kiến thức'],
    queue: ['Gọi khách đang theo', 'Đẩy booking còn mở', 'Xem tài liệu dự án mới nhất'],
  },
};

export const roleSupportBenefits = {
  admin: ['Khóa quyền và quy trình thay đổi', 'Theo dõi dữ liệu chuẩn và audit', 'Giữ hệ thống ổn định để toàn công ty vận hành trơn tru'],
  bod: ['Nhìn nhanh kinh doanh, tài chính, nhân sự', 'Ra quyết định từ một màn hình', 'Thấy ngay việc nào cần phê duyệt hoặc can thiệp'],
  manager: ['Biết đội đang tắc ở đâu', 'Theo dõi top kinh doanh và KPI đội', 'Gỡ việc quá hạn và đẩy khách nóng nhanh hơn'],
  marketing: ['Biết kênh nào đang ra khách', 'Theo dõi nội dung và chiến dịch đang chạy', 'Hỗ trợ kinh doanh bằng khách mới và nội dung đúng lúc'],
  finance: ['Nắm thu chi, công nợ và hoa hồng', 'Biết khoản nào cần đối soát ngay', 'Giảm sót số liệu trong vận hành hằng ngày'],
  hr: ['Theo dõi tuyển dụng và tiếp nhận nhân sự mới', 'Biết hồ sơ nào còn thiếu', 'Giữ nhịp đào tạo và vận hành nhân sự'],
  legal: ['Biết hồ sơ nào cần rà soát trước', 'Chuẩn bị tài liệu pháp lý để kinh doanh gửi khách', 'Giảm rủi ro từ hợp đồng và giấy tờ'],
  content: ['Biết trang nào cần cập nhật ngay', 'Theo dõi nội dung và biểu mẫu lấy khách', 'Giữ trang web luôn sẵn sàng hỗ trợ bán hàng'],
  agency: ['Theo dõi khách và giữ chỗ của mình', 'Xem ngay hoa hồng liên quan', 'Lấy tài liệu mới để đi bán nhanh hơn'],
};

export const roleDayIntent = {
  admin: {
    openingQuestion: 'Hôm nay cần khóa gì?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Không còn thay đổi cấu hình treo', 'Phân quyền và dữ liệu chuẩn được rà soát', 'Website và hệ thống không có cảnh báo nghiêm trọng'],
  },
  bod: {
    openingQuestion: 'Hôm nay cần quyết định gì?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Các điểm chờ phê duyệt quan trọng được xử lý', 'Doanh thu, cảnh báo, chiến dịch đều được nắm rõ', 'Không còn điểm mù ở kinh doanh, tài chính, nhân sự, pháp lý'],
  },
  manager: {
    openingQuestion: 'Hôm nay đội đang tắc ở đâu?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Việc quá hạn của đội được gỡ', 'Khách nóng và giữ chỗ chờ duyệt được đẩy đi', 'Top kinh doanh, KPI đội và nhịp làm việc được giữ đều'],
  },
  marketing: {
    openingQuestion: 'Hôm nay kênh nào đang ra khách?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Chiến dịch hiệu quả được ưu tiên ngân sách', 'Nội dung chờ xuất bản được đẩy đúng lúc', 'Khách mới được bàn giao cho kinh doanh nhanh và rõ'],
  },
  finance: {
    openingQuestion: 'Hôm nay khoản nào cần kiểm soát trước?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Công nợ cần đối soát được chốt rõ', 'Phiếu chi chờ duyệt không bị tồn', 'Hoa hồng và số liệu dòng tiền được kiểm soát chắc'],
  },
  hr: {
    openingQuestion: 'Hôm nay hồ sơ nào cần hoàn tất trước?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Ứng viên mới được sàng lọc kịp', 'Hồ sơ tiếp nhận không còn thiếu', 'Lịch đào tạo và nhịp nhân sự được giữ thông suốt'],
  },
  legal: {
    openingQuestion: 'Hôm nay hồ sơ nào cần rà trước?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Hợp đồng chờ ký được kiểm tra xong', 'Bộ phận kinh doanh có đủ pháp lý để gửi khách', 'Điểm rủi ro pháp lý được xử lý hoặc gắn cờ rõ'],
  },
  content: {
    openingQuestion: 'Hôm nay trang nào cần chỉnh ngay?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Trang và dự án quan trọng được cập nhật kịp', 'Nội dung chờ xuất bản không bị nghẽn', 'Biểu mẫu lấy khách và điểm chạm trang web chạy ổn'],
  },
  agency: {
    openingQuestion: 'Hôm nay khách nào dễ chốt nhất?',
    successTitle: 'Hoàn thành tốt hôm nay khi',
    successSignals: ['Khách đang theo được chăm đủ nhịp', 'Giữ chỗ mở được đẩy tiếp', 'Hoa hồng và tài liệu bán hàng luôn nắm rõ'],
  },
};

export const groupIcons = {
  tong_quan: Shield,
  tong_quan_web: Globe,
  tong_quan_he_thong: Shield,
  dieu_hanh_doi: Shield,
  chien_dich_kenh: TrendingUp,
  noi_dung: FileText,
  lead_tracking: Users,
  trang_landing: Globe,
  noi_dung_web: FileText,
  form_cta: TrendingUp,
  seo_hieu_suat: TrendingUp,
  tuyen_dung: Users,
  ho_so_nhan_su: Briefcase,
  dao_tao: FileText,
  phat_trien: TrendingUp,
  ho_so_du_an: Building2,
  tai_lieu_cho_sale: FileText,
  nguoi_dung_quyen: Shield,
  du_lieu_chuan: Shield,
  quy_trinh: Shield,
  website_cms: Globe,
  canh_bao_phe_duyet: Shield,
  thu_chi: DollarSign,
  cong_no: DollarSign,
  hoa_hong: DollarSign,
  luong_thuong: DollarSign,
  tai_lieu: FileText,
  my_team: Users,
  khach_hang: Users,
  san_pham: Building2,
  cong_viec: CheckSquare,
  ban_hang: Briefcase,
  kenh_ban_hang: TrendingUp,
  tai_chinh_sale: DollarSign,
  kinh_doanh: Briefcase,
  tai_chinh: DollarSign,
  default: LayoutDashboard,
};
